language: python
sudo: false

python:
  - "3.6"

install:
- pip install -U pip
- pip install peewee
- pip install -r dev_requirements.txt
- pip install python-coveralls

script:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m unittest tests -v ; fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls ; fi
